# Optional per-repo configuration for the Renovate->Jira agent
enabled: true

create_jira_for:
  security: true
  major: true
  critical-dep: false

critical_dependencies:
  - spring-boot
  - log4j
  - openssl

github:
  comment: false
  add_labels: false
  require_labels: ["Renovate Dependencies"]

jira:
  project: "CCD"
  labels: ["CCD-BAU", "RENOVATE-PR", "GENERATED-BY-Agent"]
  priority:
    security: "2-High"
    major: "3-Medium"
    critical-dep: "2-High"
